# Generated by Django 5.2.16 on 2026-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famtree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(blank=True, to='famtree.person'),
        ),
    ]
